---
language: ruby
cache: bundler
sudo: false

addons:
  apt:
    packages:
      - libarchive13

script: bundle exec rake travis
rvm:
  - 2.4.5
  - 2.5.3
branches:
  only:
    - master
matrix:
  fast_finish: true
