language: ruby
cache: bundler
sudo: false
distro: xenial

addons:
  apt:
    packages:
      - libarchive13

bundler_args: --jobs 7 --without docs debug

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

script: bundle exec rake travis
